name: google_maps
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_lints: ^4.0.0
  flutter_bloc: ^8.1.6
  google_maps_flutter: ^2.2.8
  google_places_autocomplete_text_field: ^0.1.3
  flutter_polyline_points: ^2.1.0
  flutter_dotenv: ^5.1.0
  location: ^6.0.2
  permission_handler: ^11.3.1
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^9.0.0
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.4
  build_runner: ^2.4.7
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  intl: any



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


